# Generated by Django 4.1.7 on 2023-02-20 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="district",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="locations.district",
                verbose_name="Distrito",
            ),
            preserve_default=False,
        ),
    ]
