# Generated by Django 4.1.7 on 2023-05-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Descripcion'),
        ),
    ]
