# Generated by Django 4.1.7 on 2023-05-10 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0003_tags_alter_jobexperience_options_jobexperience_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='current',
            field=models.BooleanField(default=False, verbose_name='Empresa actual'),
        ),
        migrations.AddField(
            model_name='education',
            name='degree',
            field=models.CharField(default=1, max_length=100, verbose_name='Grado'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='logo',
            field=models.URLField(default=1, verbose_name='Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='education',
            name='specialty',
            field=models.CharField(default=1, max_length=100, verbose_name='Especialidad'),
            preserve_default=False,
        ),
    ]
