# Generated by Django 4.1.7 on 2023-05-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0004_education_current_education_degree_education_logo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobexperience',
            options={'verbose_name': 'Experiencia profesional', 'verbose_name_plural': 'Experiencias profesionales'},
        ),
        migrations.AlterModelOptions(
            name='tags',
            options={'verbose_name': 'Tags profesional', 'verbose_name_plural': 'Tags profesionales'},
        ),
        migrations.AddField(
            model_name='jobexperience',
            name='position',
            field=models.CharField(default='Hola', max_length=150, verbose_name='Posición'),
            preserve_default=False,
        ),
    ]
