# Generated by Django 4.1.7 on 2023-05-11 05:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0005_alter_jobexperience_options_alter_tags_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='origin',
            field=models.CharField(default='q', max_length=100, verbose_name='Origen'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobexperience',
            name='description',
            field=ckeditor.fields.RichTextField(default='1'),
            preserve_default=False,
        ),
    ]
