name: Delete all build artifacts
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Delete Artifacts
        uses: actions/delete-artifacts@v0.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
