name: Delete Workflow Runs

on:
  workflow_run:
    workflows: ["Remove old artifacts"]  # Reemplaza con el nombre de tu flujo de trabajo
    types:
      - completed

jobs:
  delete_runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Delete Workflow Runs
        run: |
          token=${{ secrets.GITHUB_TOKEN }}
          owner=${{ github.repository_owner }}
          repo=${{ github.event.repository.name }}
          workflow_id=${{ github.event.workflow_id }}
          url="https://api.github.com/repos/${owner}/${repo}/actions/runs/${workflow_id}"

          echo "Deleting workflow runs for workflow: $workflow_id"

          runs=$(curl -X GET -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $token" $url | jq -r '.workflow_runs[].id')

          for run_id in $runs; do
            curl -X DELETE -H "Accept: application/vnd.github.v3+json" -H "Authorization: token $token" "https://api.github.com/repos/${owner}/${repo}/actions/runs/$run_id"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
